export const ACTIONS = {
  INPUT: 'INPUT',
  NEXTWORD: 'NEXTWORD',
  BACKSPACE: 'BACKSPACE',
  SPACE: 'SPACE',
  RESETINPUT: 'RESETINPUT',
  INPUTSTATUS: 'INPUTSTATUS',
  RESET: 'RESET',
  COMPLETE: 'COMPLETE',
  CHANGELANGUAGE: 'CHANGELANGUAGE',
  EVENTLOG: 'EVENTLOG',
};
