export const ACTIONS = {
  START: 'START',
  END: 'END',
  INPUT: 'INPUT',
  NEXTSENTENCE: 'NEXTSENTENCE',
  NEXTCHARACTER: 'NEXTCHARACTER',
  BACKSPACE: 'BACKSPACE',
  SPACE: 'SPACE',
  RESETINPUT: 'RESETINPUT',
  INPUTSTATUS: 'INPUTSTATUS',
  PINYINASSISTHINT: 'PINYINASSISTHINT',
  RESET: 'RESET',
  SET_RESETINPUT: 'SET_RESETINPUT',
  COMPLETE: 'COMPLETE',
  CHANGELANGUAGE: 'CHANGELANGUAGE',
  // Timer related actions
  UPDATETIME: 'UPDATETIME',
  EVENTLOG: 'EVENTLOG',
};
